language: node_js
sudo: false
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install hexo-cli -g
  - npm install
script:
  - hexo deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master